name: CI
on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Sphinx
        run: |
          pip install sphinx
          pip install sphinx_rtd_theme

      - name: Build
        id: build
        run: ./build.sh

      - name: Push Changes
        if: ${{ steps.build.outcome == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deployment # The branch name where you want to push the assets
          FOLDER: docs # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
